### PR TITLE
New Release for JWT Support Addon.

### PR DESCRIPTION
**Pull request by preetkaran20**
Checking for new release for JWT addon.

### CODE REVIEW

**Comment by preetkaran20** [comment]
@thc202 @kingthorin  please review. Also i have added a new release: https://github.com/SasanLabs/owasp-zap-jwt-addon/releases/tag/v1.0.1 please review that too.

thanks,
Karan

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
The release takes some manual steps. I won't be able to tackle it till next week.

**Comment by thc202** [comment]
@kingthorin you are taking care of this, right?

**Comment by kingthorin** [comment]
@preetkaran20 it's not a big deal but I just noticed that the release is titled version 2 but tagged 1.0.1.

**Comment by kingthorin** [comment]
Admin PR: https://github.com/zaproxy/zap-admin/pull/457

**Pull request merged**
