### PR TITLE
change JWTActiveScanner to JWTActiveScanRule

### LINKED ISSUE #7: ScanRule Naming Consistency
Related to: https://github.com/zaproxy/zaproxy/issues/6049

https://github.com/SasanLabs/owasp-zap-jwt-addon/blob/master/src/main/java/org/zaproxy/zap/extension/jwt/JWTActiveScanner.java should be renamed `JWTActiveScanRule` or `JwtActiveScanRule`

Of course you don't have to conform to that since this is project is 3rd party, so close/address as you see fit. But it's a pretty simple change and helps bring consistency and clarity/specificity.

### PR DESCRIPTION
**Pull request by Keenal**
changed JWTActiveScanner to JWTActiveScanRule in all the files in this repo. Let me know if I made a mistake and need to fix anything, thanks!!

fixes #7

### CODE REVIEW

**Review by preetkaran20 — APPROVED** [review]
LGTM. Thanks a lot.

**Comment by kingthorin** [comment]
https://github.blog/2013-05-14-closing-issues-via-pull-requests/

**Comment by preetkaran20** [comment]
@kingthorin can we merge this PR ?

**Review by kingthorin — APPROVED** [review]
Looks good, thanks ⭐

**Pull request merged**
